# SPDX-License-Identifier: Apache-2.0
name: "ZXF: Snyk Monitor"
# The purpose of this job is to run on each commit to the main branch and daily at midnight UTC on the most recent commit.
# This job is not intended to be run manually, but rather to be run when triggered by either a commit or the schedule.

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  snyk:
    name: Snyk Monitor
    runs-on: hl-crypto-lin-md
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: temurin
          java-version: 25.0.2

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          gradle-version: wrapper

      - name: Setup NodeJS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20

      # This step may be optional since Snyk analysis does not require the binary artifacts to be built first. However,
      # Snyk will fail if the code does not compile and the error messages are less than helpful. Therefore, we will
      # compile the code first and then run Snyk so that we can get diagnostic information if the code does not compile.
      - name: Compile
        run: ./gradlew assemble

      - name: Setup Snyk
        run: npm install -g snyk

      # For the Snyk Gradle integration to work, the configuration cache needs to be disabled and there needs to be an
      # (empty) build.gradle.kts in the root folder.
      - name: Disable Gradle Configuration Cache
        run: |
          sed -i 's/^org.gradle.configuration-cache=.*$/org.gradle.configuration-cache=false/' gradle.properties
          touch build.gradle.kts

      # This step is what actually uploads the Snyk analysis to the Snyk Cloud. The Snyk token is stored as a secret
      # in the Github repository and is passed to the Snyk CLI via the environment variable SNYK_TOKEN.
      - name: Run Snyk Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor --all-projects --org=hedera-services
